##########################################
# Role Play Basics Plugin Configurations #
##########################################

# Chat Commands
emote-message-distance: 30 # blocks
chat-distance: 30 # blocks
auto-punctuation: true # true/false

# Chat Colors
local-message-color: "&f"
local-distance-message-color: "&7"
shout-message-color: "&3"
shout-distance-message-color: "&9"
whisper-message-color: "&7"
whisper-distance-message-color: "&8"

# Messages
permission-message: "&c[RolePlayBasics]&r You do not have the necessary permission to use this command."
player-instance-message: "&c[RolePlayBasics]&r This command can only be used by players."
syntax-message: "&c[RolePlayBasics]&r Syntax: /%cmd% <message>" # Placeholder(s): %cmd%